### PR TITLE
chore(package): update ioredis to v3

### LINKED ISSUE #70: Azure redis fails
Cannot save data to Azure Redis, either on secure or non secure ports. Same code works through an open, unproxied connection to a local redis. I notice in the package.json that the ioredis version is 2.x.x. 
An update to 3.x.x solves this issue. Furthermore we cannot seem to connect to Azure Redis port (6380), Again I assume that this is due to the ioredis version that used in catbox-redis as 
Many thanks

### PR DESCRIPTION
**Pull request by AdriVanHoudt**
Fixes #70

### CODE REVIEW

**Comment by LoicMahieu** [comment]
At the same second, I created #72 ^^ Close it in favour of yours.

**Comment by AdriVanHoudt** [comment]
haha 🚀

**Comment by LoicMahieu** [comment]
+ catbox-redis@3.1.0

**Comment by LoicMahieu** [comment]
Thanks 🚀

**Pull request merged**
