### PR TITLE
Changed client instance option in favor of a factory function

### PR DESCRIPTION
**Pull request by tinchoz49**
Hi @LoicMahieu! how are you?

Yesterday I was trying to use a different redis client instance and I notice that catbox never connects to redis using a custom redis client.

Digging in the code I realized that catbox use `applyToDefaults` to the settings and that's ok but it's causing a clone of the redis client instance and that's is the issue.

If we pass a factory function returning the redis custom client everything works great.

This is a PR to change this option if you think it's ok.

### CODE REVIEW

**Comment by devinivy** [comment]
Another direction you may be able to go with this is to use [`Hoek.applyDefaultsWithShallow()'](https://github.com/hapijs/hoek/blob/master/API.md#applytodefaultswithshallowdefaults-options-keys).

**Comment by kanongil** [comment]
Wait, what? You are using it wrong. Catbox-redis does not manage the lifecycle of custom clients.

**Comment by tinchoz49** [comment]
The option exists long time and beside it's the only way to allow cluster support for catbox-redis.

**Comment by tinchoz49** [comment]
Hi @devinivy !
> Another direction you may be able to go with this is to use Hoek.applyDefaultsWithShallow().

Yes, it's true but in that case is necessary to change the applyDefaults not only in `catbox-redis` but also in `catbox` and it seems to me that can be a breaking change for the others adapters with their configurations just only because in catbox-redis the `client` option is not working. 

Maybe I wrong, what do you think?

**Comment by marcuspoehls** [comment]
@tinchoz49 Hi Martín, I'm currently reviewing your PR and have some questions: 

- do you want `catbox-redis` to manage a custom client instance, like starting and stopping it?
- what's the benefit of a factory function? (I'm not familiar with this pattern yet)

Thanks for your help!

**Comment by marcuspoehls** [comment]
Yeah, I think Redis-client management should not be the scope of `catbox-redis`.

**Comment by tinchoz49** [comment]
Hi @marcuspoehls how are you? Thanks for taking the time to review this PR.

My issue started when I try to use catbox-redis with `Redis.Cluster`. So my option was set an ioredis client with cluster support into the catbox-redis using the option `client`.

The problem is that during the setup of catbox with catbox-redis catbox does a clone of the object settings and clone the redis client that is trying to connect to redis.

Encapsulating the redis client in a function solves this problem.

btw I noticed that this PR was old, I just updated. 

@kanongil 

> This breaks the existing functionality, which allows a pre-started / shared client to be used.

Of course. For those cases, we have the major version update. Did you try to use hapi with catbox-redis and a shared client?

The only way that is working right now is waiting for the shared client `ready` event connection and then initialize the catbox-redis (like how currently are working the tests related to this).

For example, this doesn`t work:

```javascript
const Catbox = require('catbox')
const CatboxRedis = require('catbox-redis')
const Redis = require('ioredis')

const redisClient = new Redis()

;(async () => {
  const client = new Catbox.Client(CatboxRedis, {
    client: redisClient
  })

  await client.start()

  console.log(`is ready ${client.isReady()}`)

  try {
    const key = { id: 'x', segment: 'test' }
    await client.set(key, 'test', 0)
    console.log('value set')
  } catch (err) {
    console.log(err.message)
  }
})()
```

**Comment by marcuspoehls** [comment]
@tinchoz49 @kanongil @kanongil Hey everyone, I can see where the problem is.

`ioredis` automatically connects to the Redis server when instantiating a new `client`. That means, `catbox-redis` won't notice the `ready` event, because it's fired before `catbox-redis` listens for it.

Martín is right, if the custom client isn't connected and ready when passing it as the `client` option into `catbox-redis`, it won't be started.

What do you think about this approach: if a `client` is passed as an option, `catbox-redis` creates a new Redis client based on the options of the passed `client`?

```js
start() {

    if (this.client) {
        return Promise.resolve();
    }

    // Return a promise that is resolved when everything is ready
    return new Promise((resolve, reject) => {

        let client

        if (this.settings.client) {
            client = Redis.createClient(this.settings.client.options)
        } else {
            const options = Object.assign({}, this.settings, {
                db: this.settings.database || this.settings.db,
                name: this.settings.sentinelName,
                tls: this.settings.tls
            });

            client = Redis.createClient(options)
        }

        // Listen to errors
        client.on('error', (err) => { … });

        // Wait for connection
        client.once('ready', () => { … });
    });
}
```

This allows `catbox-redis` to listen for the `ready` event.
Let me know your thoughts.

**Comment by marcuspoehls** [comment]
I have another idea for this client handling. I'll check it tomorrow and let you know. The basic idea is to use another way of connecting via ioredis. Instead of using an event, we can connect directly. This might help to solve the issues around clients not connected.

It might not solve all problems, e.g. when someone supplies another Redis client than ioredis.

Need to think about that before making changes towards ioredis that may be incompatible with other clients.

**Comment by marcuspoehls** [comment]
Hi all,

I noticed that `ioredis` is close to release a new major version: `4.0.0`:
https://github.com/luin/ioredis/releases/tag/v4.0.0-0

In `ioredis` 4.0, the `connect()` function will resolve when the connection is `ready`, which will solve all the problems around a custom `ioredis` client not being connected. This allows everyone to connect before injecting the `client` as an option into `catbox-redis`.

@tinchoz49 Do you think `ioredis 4.0` will solve the problem?

**Comment by marcuspoehls** [comment]
@tinchoz49 Just checking in. Do you think `ioredis 4.0` will simplify the custom `client` handling that users run into these days?

**Comment by tinchoz49** [comment]
Hi @marcuspoehls !! really sorry for the late in answer, it was a busy week.

I think it could work because in that case, we are going to stop sharing the connection state from the begin and use it only on the catbox initialization.

> What do you think about this approach: if a client is passed as an option, catbox-redis creates a new Redis client based on the options of the passed client?

This is going to work too at least the issue related to sharing the connection state.

There is another issue that I'm trying to solve with this PR and it's allow to the developer use redis clusters with catbox-redis. https://github.com/hapijs/catbox-redis/pull/84

Right now I'm using in production something like this and it works with this PR:

manifest.js
```javascript
...
    cache: [
      {
        engine: 'catbox-redis',
        client() {
          return new Redis.Cluster([
              {
                port: 6380,
                host: '127.0.0.1'
              },
              {
                port: 6381,
                host: '127.0.0.1'
              }
          ]);
        }
      }
    ]
...
```

**Comment by tinchoz49** [comment]
btw I take the idea of using a function to set the redis client from: https://github.com/OptimalBits/bull/blob/master/PATTERNS.md#reusing-redis-connections

**Comment by marcuspoehls** [comment]
@tinchoz49 Hey Martín, do you think `ioredis v4` provides everything needed to solve this problem?

In ioredis v4 you can `await client.connect()` and pass the client instance to catbox. Is that what you’re looking for?

Nonetheless, I actually like the idea of a factory function for the client. But I’m hesitant to allow too much logic around the Redis client instance inside of catbox-redis. Even a function might confuse some users

**Comment by marcuspoehls** [comment]
@tinchoz49 Martín, thank you for work contribution :+1: I really appreciate your support!

I'm closing this PR here because I think that ioredis v4 provides a nice interface to pass in a "ready-to-go" client.

Please don't hesitate to reopen if we should discuss in more depth

**Pull request closed without merging**
