### PR TITLE
Adding the ability to connect to a Redis cluster.

### PR DESCRIPTION
**Pull request by Crispy1975**
I have added the ability to connect to a Redis cluster (along with a supporting test). To test Redis needs to be started in cluster mode by enabling in the `redis.conf`. Also updated the README.md etc.

Let me know what you think.

### CODE REVIEW

**Comment by Crispy1975** [comment]
I should add I don't think Travis support running a Redis cluster for tests, I've seen a project that builds one using a `Makefile` but might be worth disabling that test?

**Comment by marcuspoehls** [comment]
@Crispy1975 @svnlto Do you know of a way to simply spin up a Redis cluster for testing? We shouldn't add cluster functionality without proper testing.

**Comment by Crispy1975** [comment]
@marcuspoehls as @svnlto mentioned the easiest way would probably be to make use of Docker Compose and have a yaml file defining the service. Given some time I will see what I can do around this for making the cluster stuff testable.

**Comment by marcuspoehls** [comment]
@Crispy1975 That would be great. Please go ahead and make cluster functionality testable. Thank you!

**Comment by marcuspoehls** [comment]
@Crispy1975 Hey Crispy, how's it going? Did you had the chance to proceed on the cluster testing?

I've added a "Redis mock server" that might be helpful for testing. It would be nice to use the mock server for this tests to avoid dependencies on a local Docker setup.

Let me know if you don't proceed with Cluster testing. I'd take it over.

Thank you! Have a nice weekend :)

**Comment by Crispy1975** [comment]
Hey @marcuspoehls this totally dropped off of my radar due to work commitments, but it's something I am still willing to work on. I'll put some time to the side this week for it. :+1:

**Comment by marcuspoehls** [comment]
@Crispy1975 Great, thank you!

**Comment by marcuspoehls** [comment]
@Crispy1975 Hey Crispy, I don't wanna put extra pressure on you with this PR. I want to ask if I help you with something? Do you need an example for cluster testing with the mock server?

PS: is Crispy your real name? I don't want to be rude calling you that name if it isn't yours.

**Comment by Crispy1975** [comment]
Hey @marcuspoehls things are a little chaotic with time right now, I have this on my list of things to get to, but if you are able to make a start then that would be awesome. :+1: 

Crispy... not my real name, but y'know, it's the Internet. :-)

**Comment by klaemo** [comment]
Is there anything anyone can do to help this along? @Crispy1975 It's fine if you don't have the time to finish this, I think. Someone else could take over.

**Comment by hueniverse** [comment]
@klaemo feel free to jump in and help resolve it.

**Comment by marcuspoehls** [comment]
@klaemo Hi Clemens, this repo has another PR https://github.com/hapijs/catbox-redis/pull/94 that is further along with cluster support.

I’ll close this here.

**Pull request closed without merging**
