### PR TITLE
Added ability to select database

### PR DESCRIPTION
**Pull request by juliusrickert**

### CODE REVIEW

**Comment by hueniverse** [comment]
@LoicMahieu you are all set.

**Comment by LoicMahieu** [comment]
@hueniverse Thanks.

@juliusrickert Back to your PR. Thanks for contribution.
It's good to mention that database model in redis is discouraged by the devs, see https://groups.google.com/forum/#!topic/redis-db/u1IgtiWN0Ww
http://stackoverflow.com/questions/16221563/whats-the-point-of-multiple-redis-databases
Furthermore redis-cluster does not support multiple database.

Anyway I think it can be merged into catbox-redis. Your PR need to be rebased. Please rebase it into 1 commit.

**Comment by juliusrickert** [comment]
Should I open a new pr or can I just post a new commit inside this one?

**Comment by LoicMahieu** [comment]
You can rebase your branch and `git push --force` on `juliusrickert:master`. It will update the PR automatically.
If you are not confortable with rebase, read excellent
http://git-scm.com/book/en/v2/Git-Branching-Rebasing
https://help.github.com/articles/about-git-rebase/

**Comment by juliusrickert** [comment]
I really don't get how to do this :(

Now everything is screwed up :(

**Comment by LoicMahieu** [comment]
Ok no problem. I will make a new PR #16 with your modifications. You can now reset your branch:
```
$ git remote add catbox https://github.com/hapijs/catbox-redis.git
$ git fetch catbox
$ git reset --hard catbox/master
```

For your information, here is how I recover your code:
```
$ git remote add juliusrickert https://github.com/juliusrickert/catbox-redis.git
$ git fetch --all
$ git checkout -b juliusrickert-PR13
$ git cherry-pick juliusrickert/master~4 juliusrickert/master~3 juliusrickert/master~2 juliusrickert/master~1 juliusrickert/master~0
$ git rebase -i HEAD~5
pick 0cf5c8e Added ability to select database
squash 27ed37a Update README.md
squash 9b6fc30 Added database selection test
squash 2e3baa3 Update index.js
squash b43aecf Update index.js
$ git push origin juliusrickert-PR13:juliusrickert-PR13
```

**Pull request closed without merging**
