### PR TITLE
Sentinel support

### LINKED ISSUE #65: Sentinel Support
We recently [forked](https://github.com/WatchBeam/catbox-redis) this repo in order to add native sentinel config support to it.

I'd like to pull request this, but adding a full sentinel integration tests would require me to add a full sentinel config and another 2 redis instances.

Would it be sufficient to mock out `ioredis` and simply check if it was called with the right arguments?

### PR DESCRIPTION
**Pull request by SimonSchick**
Closes #65 

I used an empty `describe` call to scope my `before` and `after` calls, that okay?
Not really experienced with `lab` and `code`, any better/cleaner way to do this?

### CODE REVIEW

**Comment by SimonSchick** [comment]
@LoicMahieu and @hueniverse for review pretty please?

**Comment by SimonSchick** [comment]
@LoicMahieu please? 🙂

**Comment by AdriVanHoudt** [comment]
@SimonSchick you have to understand that this module is being maintained in people's free time.
I am sure @LoicMahieu has gotten the notification and will get around to review your PR. More than 1 ping, and definitely so soon, does not make things go faster.

**Comment by SimonSchick** [comment]
@AdriVanHoudt I am very well aware, I usually send a second message after a few days in case the first one was missed, which happens surprisingly often, I don't need a lecture 🙂

**Comment by AdriVanHoudt** [comment]
@SimonSchick not a lecture :O in 99% of the cases the person is not aware of this or doesn't care

**Comment by SimonSchick** [comment]
@LoicMahieu any chance you can look at this now?

**Comment by LoicMahieu** [comment]
Hi @SimonSchick 
Thanks for your PR! As said by @AdriVanHoudt , I do the best effort for review my Github notifications regularly but time is missing, for everyone I suppose ;)

Anyway, great PR! I don't have a specific problem with empty describe.

Thanks for your patience, ready to merge!

**Comment by LoicMahieu** [comment]
+ catbox-redis@3.0.2

**Comment by SimonSchick** [comment]
@LoicMahieu Thanks!

**Pull request merged**
