### PR TITLE
Task: Support read replica

### PR DESCRIPTION
**Pull request by niklasR**
WIP for #61.

Not at 100% coverage yet, need to figure out how to test connection failure independently from the master.

Suggestions and any other feedback welcome :)

### CODE REVIEW

**Comment by niklasR** [comment]
I did also just realise that [ioredis](https://github.com/luin/ioredis) supports clustering out of the box, which might be easier, rather than trying to re-invent the wheel here.

**Comment by marcuspoehls** [comment]
@niklasR Hey Nik, I'm currently reviewing your PR. 

This is an extensive change to `catbox-redis`. Do you think passing in a custom client instance would solve this as well?

Merging your PR would put `catbox-redis` in charge of features from `ioredis` instead of handling caching. 

Do you agree to keep this outside of catbox-redis?

**Comment by niklasR** [comment]
Hi @marcuspoehls, thanks for having a look!

Yes, I agree, it is probably something better suited for the actual redis library handling the connections and not a catbox wrapper. For our use case we've implemented it in the redis library, and use standard catbox-redis

**Comment by marcuspoehls** [comment]
@niklasR Awesome! Your solution sounds nice :)

I'll close your PR. Just let me know if we missed something or need new functionality :)
Have a great day!

**Pull request closed without merging**
